config/routes.rb
Rails.application.routes.draw do
  resources :high_scores

  get 'verses' => 'page#verses'
  get 'finished' => 'page#finished'
  get 'answered' => 'page#answered'
  get 'usage' => 'page#usage'
  get 'report' => 'page#report'
  get 'gratitudes' => 'page#gratitudes'
  get 'users' => 'page#users'
  get 'bg_rating' => 'page#bg_rating'
  get 'users_count' => 'page#users_count'
  get 'delete_users' => 'page#delete_users'
  get 'memorized_verses' => 'page#memorized_verses'
  get 'memorized_stats' => 'page#memorized_stats'
  get 'memorized_verses_with_count' => 'page#memorized_verses_with_count'
  get 'memorized_stats_weekly' => 'page#memorized_stats_weekly'
  get 'menu' => 'page#menu'
  get 'add_gratitude' => 'page#add_gratitude'
  get 'get_gratitudes' => 'page#get_gratitudes'
  get 'startup_data' => 'page#startup_data'
  get 'add_favorite' => 'page#add_favorite'
  get 'remove_favorite' => 'page#remove_favorite'
  get 'favorite_count' => 'page#favorite_count'
  get 'is_favorite' => 'page#is_favorite'
  get 'all_favorites' => 'page#all_favorites'
  get 'get_recent_favorites' => 'page#get_recent_favorites'
  get 'get_recent_activities' => 'page#get_recent_activities'
  get 'get_chats' => 'page#get_chats'
  get 'add_chat' => 'page#add_chat'

end

app/views/page/gratitudes.html.haml
%h1 "Praise the Lord; for the Lord is good: sing praises unto his name; for it is pleasant”
%h2 (Psalms 135:3)
%hr
- @gratitudes.each do |g|
  %p= "#{g.text} - #{g.user_name}, #{time_ago_in_words(g.created_at)} ago"

app/views/page/report.html.haml
%p
  = link_to 'default', report_path()
  = link_to 'sort by users', report_path(sort: 'users')
  = link_to 'sort by time', report_path(sort: 'time')

%p New users in the last 3 days
- @new_users.each do |user|
  = "#{user}, "

%h2 User count
- @usage_by_date.each do |usage_by_date|
  %div= "#{usage_by_date[0]} #{usage_by_date[1]}"

-#%h2 Overall duration
-#%table{ border: 1}
-#  %tr
-#    %td user name
-#    %td count
-#    %td max
-#    %td min
-#    %td duration
-#  - @overall_duration.each do |row|
-#    %tr
-#      - row.each do |cell|
-#        %td= cell[1]
-#
-#%h2 Played count
-#%table{ border: 1}
-#  %tr
-#    %td user name
-#    %td count
-#    %td max
-#    %td min
-#    %td duration
-#  - @played_count.each do |row|
-#    %tr
-#      - row.each do |cell|
-#        %td= cell[1]

%h2 Most Fav Users
%table{ border: 1}
  %tr
    %td user name
    %td count
  - @most_fav_users.each do |row|
    %tr
      - row.each do |cell|
        %td= cell

%h2 Most Fav Verses
%table{ border: 1}
  %tr
    %td plan_id
    %td day
    %td count
  - @most_fav_verses.each do |row|
    %tr
      - row.each do |cell|
        %td= cell

%h2 Log
%table{ border: 1}
  %tr
    %td user name
    %td ip
    %td usage_type
    %td details
    %td plan id
    %td day
    %td created_at

  - @users.each do |usage|
    %tr
      %td= usage.user_name
      %td= usage.ip
      %td= usage.usage_type
      %td= usage.details
      %td= usage.plan_id
      %td= usage.day
      %td= usage.created_at.in_time_zone("Pacific Time (US & Canada)")